In [1]:
import pandas as pd

In [8]:
df=pd.read_csv("Employee_Salary_Dataset.csv")

In [9]:
import numpy as np

In [10]:
import matplotlib

In [11]:
df

    ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [15]:
df.describe()

              ID  Experience_Years        Age        Salary
count  35.000000          35.00000  35.000000  3.500000e+01
mean   18.000000           9.20000  35.485714  2.059147e+06
std    10.246951           7.55295  14.643552  3.170124e+06
min     1.000000           1.00000  17.000000  3.000000e+03
25%     9.500000           2.50000  22.500000  2.250000e+04
50%    18.000000           6.00000  29.000000  2.500000e+05
75%    26.500000          15.00000  53.500000  3.270000e+06
max    35.000000          27.00000  62.000000  1.000000e+07

In [18]:
df.mean(numeric_only=True)

ID                  1.800000e+01
Experience_Years    9.200000e+00
Age                 3.548571e+01
Salary              2.059147e+06
dtype: float64

In [19]:
df.loc[:,'Age'].mean()

np.float64(35.48571428571429)

In [57]:
mean=df["Salary"].mean()

In [21]:
df["Salary"].mean()

np.float64(2059147.142857143)

In [22]:
df.mean(axis=1)[0:4]

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [23]:
df[["ID","Experience_Years","Age","Salary"]].mean(axis=1)[0:4]

0    62508.50
1    12506.00
2    42507.25
3     6257.00
dtype: float64

In [60]:
median=df[["ID","Experience_Years","Age","Salary"]].median()

In [61]:
median

ID                      18.0
Experience_Years         6.0
Age                     29.0
Salary              250000.0
dtype: float64

In [26]:
df.loc[:,'Age'].median()

29.0

In [27]:
df[["ID","Experience_Years","Age","Salary"]].median(axis=1)[0:4]

0    16.5
1    11.5
2    13.0
3    13.0
dtype: float64

In [28]:
df.mode()

    ID  Experience_Years   Age  Gender    Salary
0    1               2.0  54.0  Female   25000.0
1    2               NaN   NaN     NaN  250000.0
2    3               NaN   NaN     NaN       NaN
3    4               NaN   NaN     NaN       NaN
4    5               NaN   NaN     NaN       NaN
5    6               NaN   NaN     NaN       NaN
6    7               NaN   NaN     NaN       NaN
7    8               NaN   NaN     NaN       NaN
8    9               NaN   NaN     NaN       NaN
9   10               NaN   NaN     NaN       NaN
10  11               NaN   NaN     NaN       NaN
11  12               NaN   NaN     NaN       NaN
12  13               NaN   NaN     NaN       NaN
13  14               NaN   NaN     NaN       NaN
14  15               NaN   NaN     NaN       NaN
15  16               NaN   NaN     NaN       NaN
16  17               NaN   NaN     NaN       NaN
17  18               NaN   NaN     NaN       NaN
18  19               NaN   NaN     NaN       NaN
19  20               NaN   NaN     NaN       NaN
20  21               NaN   NaN     NaN       NaN
21  22               NaN   NaN     NaN       NaN
22  23               NaN   NaN     NaN       NaN
23  24               NaN   NaN     NaN       NaN
24  25               NaN   NaN     NaN       NaN
25  26               NaN   NaN     NaN       NaN
26  27               NaN   NaN     NaN       NaN
27  28               NaN   NaN     NaN       NaN
28  29               NaN   NaN     NaN       NaN
29  30               NaN   NaN     NaN       NaN
30  31               NaN   NaN     NaN       NaN
31  32               NaN   NaN     NaN       NaN
32  33               NaN   NaN     NaN       NaN
33  34               NaN   NaN     NaN       NaN
34  35               NaN   NaN     NaN       NaN

In [29]:
df.loc[:,'Age'].mode()

0    54
Name: Age, dtype: int64

In [30]:
df.min()

ID                       1
Experience_Years         1
Age                     17
Gender              Female
Salary                3000
dtype: object

In [31]:
df.loc[:,'Age'].min(skipna = False)

np.int64(17)

In [32]:
df.max()

ID                        35
Experience_Years          27
Age                       62
Gender                  Male
Salary              10000000
dtype: object

In [33]:
df.loc[:,'Age'].max(skipna = False)

np.int64(62)

In [34]:
df.std()

TypeError: could not convert string to float: 'Female'

In [35]:
df[["ID","Experience_Years","Age","Salary"]].std()

ID                  1.024695e+01
Experience_Years    7.552950e+00
Age                 1.464355e+01
Salary              3.170124e+06
dtype: float64

In [36]:
df.loc[:,'Age'].std()

14.643551940884361

In [38]:
df[["ID","Experience_Years","Age","Salary"]].std(axis=1)[0:4]

0    124994.333900
1     24996.001694
2     84995.167190
3     12495.336570
dtype: float64

In [40]:
df.groupby(['Gender'])['Age'].mean()

Gender
Female    37.111111
Male      33.764706
Name: Age, dtype: float64

In [41]:
df_u=df.rename(columns= {'Annual Income k$)':'Income'},inplace=False)

In [45]:
df_u.groupby(['Gender']).Salary.mean()

Gender
Female    2.054917e+06
Male      2.063626e+06
Name: Salary, dtype: float64

In [47]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Gender']]).toarray())

In [48]:
enc

OneHotEncoder()

In [49]:
enc_df

      0    1
0   1.0  0.0
1   0.0  1.0
2   1.0  0.0
3   0.0  1.0
4   0.0  1.0
5   0.0  1.0
6   1.0  0.0
7   1.0  0.0
8   1.0  0.0
9   1.0  0.0
10  1.0  0.0
11  0.0  1.0
12  0.0  1.0
13  0.0  1.0
14  0.0  1.0
15  1.0  0.0
16  1.0  0.0
17  1.0  0.0
18  0.0  1.0
19  0.0  1.0
20  0.0  1.0
21  0.0  1.0
22  0.0  1.0
23  1.0  0.0
24  1.0  0.0
25  1.0  0.0
26  0.0  1.0
27  1.0  0.0
28  1.0  0.0
29  1.0  0.0
30  0.0  1.0
31  0.0  1.0
32  1.0  0.0
33  1.0  0.0
34  0.0  1.0

In [50]:
df_encode =df_u.join(enc_df)

In [51]:
df_encode

    ID  Experience_Years  Age  Gender    Salary    0    1
0    1                 5   28  Female    250000  1.0  0.0
1    2                 1   21    Male     50000  0.0  1.0
2    3                 3   23  Female    170000  1.0  0.0
3    4                 2   22    Male     25000  0.0  1.0
4    5                 1   17    Male     10000  0.0  1.0
5    6                25   62    Male   5001000  0.0  1.0
6    7                19   54  Female    800000  1.0  0.0
7    8                 2   21  Female      9000  1.0  0.0
8    9                10   36  Female     61500  1.0  0.0
9   10                15   54  Female    650000  1.0  0.0
10  11                 4   26  Female    250000  1.0  0.0
11  12                 6   29    Male   1400000  0.0  1.0
12  13                14   39    Male   6000050  0.0  1.0
13  14                11   40    Male    220100  0.0  1.0
14  15                 2   23    Male      7500  0.0  1.0
15  16                 4   27  Female     87000  1.0  0.0
16  17                10   34  Female    930000  1.0  0.0
17  18                15   54  Female   7900000  1.0  0.0
18  19                 2   21    Male     15000  0.0  1.0
19  20                10   36    Male    330000  0.0  1.0
20  21                15   54    Male   6570000  0.0  1.0
21  22                 4   26    Male     25000  0.0  1.0
22  23                 5   29    Male   6845000  0.0  1.0
23  24                 1   21  Female      6000  1.0  0.0
24  25                 4   23  Female      8900  1.0  0.0
25  26                 3   22  Female     20000  1.0  0.0
26  27                 1   18    Male      3000  0.0  1.0
27  28                27   62  Female  10000000  1.0  0.0
28  29                19   54  Female   5000000  1.0  0.0
29  30                 2   21  Female      6100  1.0  0.0
30  31                10   34    Male     80000  0.0  1.0
31  32                15   54    Male    900000  0.0  1.0
32  33                20   55  Female   1540000  1.0  0.0
33  34                19   53  Female   9300000  1.0  0.0
34  35                16   49    Male   7600000  0.0  1.0

In [54]:
skwness=(3*(mean-median))/sd

NameError: name 'mean' is not defined

In [55]:
sd=df['Salary'].std()

In [62]:
skewness=(3*(mean-median))/sd
print(f"Skewness={skewness}")

Skewness=ID                  1.948627
Experience_Years    1.948638
Age                 1.948616
Salary              1.712060
dtype: float64